[interferometric_analysis]
enable_coherence_computation = false        # enable/disable coherence computation (to be enabled for interferogram products)
coherence_kernel = [15, 15]                 # kernel size for coherence computation
azimuth_blocks_number = 1                   # number of azimuth blocks for computing coherence 2D histogram
range_blocks_number = 1                     # number of range blocks for computing coherence 2D histogram
coherence_bins_number = 80                  # number of coherence intensity bins